---

- name: "Ubuntu 22.04 - Install Node v12 + NPM v8 (default)"
  apt:
    state: latest
    name:
      - nodejs
      - npm
      - gulp
  when: node_use_legacy_version == true

# Reference: https://github.com/nodesource/distributions#manual-installation

- name: "Ubuntu 22.04 - Add Node APT Repository key"
  get_url:
    force: true
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    dest: /etc/apt/trusted.gpg.d/nodesource.asc
    mode: '0644'
  when: node_use_legacy_version != true

- name: "Ubuntu 22.04 - Add Nodesource sources"
  lineinfile:
    create: yes
    path: /etc/apt/sources.list.d/nodesource.list
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "deb [arch=amd64] https://deb.nodesource.com/node_{{ node_latest_version }}.x jammy main"
    - "deb-src [arch=amd64] https://deb.nodesource.com/node_{{ node_latest_version }}.x jammy main"
  when: node_use_legacy_version != true

# - name: "Ubuntu 20.04 - Install Node v18 + NPM (latest)"
- name: "Ubuntu 20.04 - Install Node v{{ node_latest_version }} + NPM (latest)"
  apt:
    update_cache: yes
    state: latest
    name: nodejs
  when: node_use_legacy_version != true

- name: "Ubuntu 20.04 - Install NPM global packages (latest)"
  npm:
    global: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - gulp-cli
    # add more later
  when: node_use_legacy_version != true
