---

- name: "Ubuntu 20.04 - Install Node v10 + NPM (default)"
  apt:
    state: latest
    name:
      - nodejs
      - npm
      - node-grunt-cli
      - gulp
  when: node_use_legacy_version == true

# Reference: https://github.com/nodesource/distributions#manual-installation

- name: "Ubuntu 20.04 - Add Node APT Repository key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  when: node_use_legacy_version != true

- name: "Ubuntu 20.04 - Add Nodesource sources"
  lineinfile:
    create: yes
    path: /etc/apt/sources.list.d/nodesource.list
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "deb [arch=amd64] https://deb.nodesource.com/node_{{ node_latest_version }}.x focal main"
    - "deb-src [arch=amd64] https://deb.nodesource.com/node_{{ node_latest_version }}.x focal main"
  when: node_use_legacy_version != true

- name: "Ubuntu 20.04 - Install Node v{{ node_latest_version }} + NPM (latest)"
  apt:
    update_cache: yes
    state: latest
    name:
      - nodejs
      - gulp
  when: node_use_legacy_version != true
