---

- name: "Install NodeJS"
  apt: name=nodejs state=latest

- name: Install Grunt CLI
  apt: name=node-grunt-cli state=latest

# Work around for Grunt problems with prebuilt canvas library
- name: Install libpng12
  apt: deb="http://archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb" state=present
